# -*- coding: utf-8 -*-
"""Диалоги Jimaku: источник настоящий, Gemini только переводит."""
from contextlib import nullcontext
import random
import threading
import xml.etree.ElementTree as ET

import animepack as ap
import animepack_api as api


SRT = """1
00:01:00,000 --> 00:01:02,000
Why did you come back here?

2
00:01:02,200 --> 00:01:04,000
Because I promised I would find the truth.

3
00:01:04,100 --> 00:01:06,000
Then we should open the old door together.
""".encode()


class Response:
    def __init__(self, data, status=200, content=b""):
        self._data = data
        self.status_code = status
        self.content = content

    def json(self):
        return self._data

    def raise_for_status(self):
        if self.status_code >= 400:
            raise RuntimeError(self.status_code)


class Session:
    def __init__(self):
        self.calls = []

    def get(self, url, **kwargs):
        self.calls.append((url, kwargs))
        if url.endswith("/entries/search"):
            return Response([
                {"id": 1, "anilist_id": 99, "flags": ["anime", "unverified"]},
                {"id": 2, "anilist_id": 99, "flags": ["anime"]},
            ])
        if url.endswith("/entries/2/files"):
            return Response([
                {"name": "Title - 07.ass", "url": "https://cdn/sub.ass?token=x"},
                {"name": "Title - 01-12.ass", "url": "https://cdn/batch.ass"},
                {"name": "Title - 07 [Generated by Whisper].srt",
                 "url": "https://cdn/ai.srt"},
            ])
        return Response({}, content=SRT)


class Gemini:
    def generate_json(self, _prompt, _schema, temperature=0.0):
        assert temperature == 0.0
        return {"lines": [
            {"source": "Why did you come back here?",
             "translation": "Почему ты вернулся сюда?",
             "contains_name": False},
            {"source": "Because I promised I would find the truth.",
             "translation": "Потому что я обещал найти правду.",
             "contains_name": False},
        ]}


def anime():
    return {"malId": 1, "name": "Test", "russian": "Тест",
            "english": "Test", "kind": "tv", "score": 8.0,
            "airedOn": {"year": 2020}, "synonyms": []}


def test_client_uses_authorization_and_rejects_unverified_batches_and_ai():
    session = Session()
    client = api.JimakuApi("secret", session=session)
    assert client.entry(99)["id"] == 2
    files = client.files(2, 7)
    assert [row["name"] for row in files] == ["Title - 07.ass"]
    assert all(call[1]["headers"]["Authorization"] == "secret"
               for call in session.calls)
    assert api.jimaku_clean_source_url(files[0]["url"]) == "https://cdn/sub.ass"


def test_generator_records_episode_source_and_gemini_translation_only():
    class AniZip:
        def anilist_id(self, _mal): return 99
        def episode_numbers(self, _mal): return [7]

    class Jimaku:
        def entry(self, _aid): return {"id": 2}
        def files(self, _entry, _ep):
            return [{"name": "Title - 07.srt",
                     "url": "https://cdn/sub.srt?secret=gone"}]
        def download(self, _file): return SRT

    class TranslatingGemini:
        def generate_json(self, prompt, _schema, temperature=0.0):
            # Серия приходит целиком; модель выбирает реплики 0–1 и
            # переводит их.
            assert "2: Then we should open the old door" in prompt
            return {"found": True, "start": 0, "count": 2, "clue": "дверь",
                    "lines": [{"translation": f"Перевод {i + 1}.",
                               "contains_name": False} for i in range(2)]}

    gen = object.__new__(ap.AnimePackGenerator)
    gen.jimaku = Jimaku()
    gen.gemini = TranslatingGemini()
    gen.anizip = AniZip()
    gen.rng = random.Random(0)
    gen._dialogue_lock = threading.Lock()
    gen._dialogue_seen = set()
    gen._timed = lambda _name: nullcontext()
    gen._drop_kind = lambda _kind: None
    gen._log_rare = lambda *_args: None
    gen.log = lambda _message: None
    cand = ap.SongCandidate({}, anime(), kind=ap.DIALOGUE_KIND)
    assert ap.AnimePackGenerator.make_dialogue_question(gen, cand)
    assert cand.dialogue_episode == 7
    assert cand.dialogue_text.startswith("— Перевод 1.")
    assert cand.source_link == "https://cdn/sub.srt"
    assert "Перевод" not in cand.dialogue_source_text
    assert cand.dialogue_source_text.startswith("— Why did you come back")


def test_xml_speaks_only_plain_episode_number_for_dialogue():
    settings = ap.PackSettings(rounds=1, themes=1, questions=1,
                               pct_songs=0, pack_dialogue=True,
                               pct_dialogue=100, gemini_key="g", jimaku_key="j")
    cand = ap.SongCandidate({}, anime(), kind=ap.DIALOGUE_KIND,
                            users=["Игрок"], author_name="Автор")
    cand.dialogue_text = "— Почему ты вернулся?\n— Я обещал найти правду."
    cand.dialogue_episode = 7
    cand.source_link = "https://cdn/sub.srt"
    root = ET.fromstring(ap.build_content_xml([cand], settings))
    ns = {"s": ap.SIQ_NS}
    question = [item.text for item in root.findall(
        ".//s:param[@name='question']/s:item", ns)]
    assert question == [cand.dialogue_text]
    spoken = [item.text for item in root.findall(
        ".//s:param[@name='answer']/s:item", ns)
              if item.get("placement") == "replic"]
    assert spoken == ["Серия 7"]
    assert "https://cdn/sub.srt" in [item.text for item in root.findall(
        ".//s:right/s:answer", ns)]


def test_dialogue_requires_both_api_keys_and_has_its_own_quota():
    settings = ap.PackSettings(pct_songs=0, pack_dialogue=True,
                               pct_dialogue=100)
    assert settings.question_quotas[ap.DIALOGUE_KIND] == settings.total_questions
    problems = " ".join(settings.validate())
    assert "Gemini" in problems and "Jimaku" in problems
    settings.gemini_key = "g"
    settings.jimaku_key = "j"
    problems = " ".join(settings.validate())
    assert "Gemini" not in problems and "Jimaku" not in problems


